my notes/code for: https://www.coursera.org/learn/machine-learning/lecture/FuSWY/inverse-and-transpose

"It turns out that sometimes you can compute inverses by hand but almost no one does that these days. And it turns out there is very good numerical software for taking a matrix and computing its inverse. So again, this is one of those things where there are lots of open source libraries that you can link to from any of the popular programming languages to compute inverses of matrices." - Andrew Ng


Andrew uses Octave to compute the inverse of a matrix but let's try using numpy instead.

Keynotes from lesson:
- a *square matrix* is a matrix with the same # of rows and columns
- you can only compute the inverse of a square matrix; matricies that don't have an inverse are *singular* or *degenerate*
- the inverse of a matrix A is denoted as A-1.

In [1]:
# computing the inverse of a matricies using numpy
import numpy as np

# create matrix
a = np.array([[3, 4], [2, 16]])
a

array([[ 3,  4],
       [ 2, 16]])

In [2]:
# compute matrix inverse
ainv = np.linalg.inv(a)
ainv

array([[ 0.4  , -0.1  ],
       [-0.05 ,  0.075]])

In [3]:
# "reinverse" inversed matrix
np.linalg.inv(ainv)

array([[ 3.,  4.],
       [ 2., 16.]])

Let's now test the rule mentioned in the video using numpy.

![matrix_inverse_rule](https://user-images.githubusercontent.com/53675680/62815902-61a92000-baed-11e9-8fbf-bbfa32c2fc93.PNG)

<i>I</i> denotes an *Identity Matrix*. For an explanation of what an identity matrix is please see: https://www.coursera.org/learn/machine-learning/lecture/W1LNU/matrix-multiplication-properties

In [4]:
# create 2x2 indentity matrix
ident = np.identity(2)

In [5]:
np.dot(a, ainv)

array([[1., 0.],
       [0., 1.]])

In [6]:
np.dot(ainv, a)

array([[1., 0.],
       [0., 1.]])

Verified!

Let's finish off with transposing a matrix using numpy.

![matrix_transpose](https://user-images.githubusercontent.com/53675680/62815999-c2852800-baee-11e9-8203-8fb992a32f69.PNG)

In [7]:
b = np.array([[1, 2, 0], [3, 5, 9]])
b

array([[1, 2, 0],
       [3, 5, 9]])

In [8]:
btrans = np.transpose(b)
btrans

array([[1, 3],
       [2, 5],
       [0, 9]])